### ISSUE TITLE
Third Person Crosshair Passes Through Players

### ISSUE THREAD

**Issue by ottworks** [BSVino/DoubleAction#76]
![](http://i.imgur.com/y8i3o82.png)

Aiming for headshots is significantly harder in third person, as you have to compensate for your crosshair thinking you want to shoot past them:

![](http://i.imgur.com/ctpamp7.png)

**Comment by BSVino** [comment]
This is by design. You have a parallax problem. The smaller crosshair shows you where your bullet will go. The alternative is that your firing angle changes drastically between short and long range. I think I tried it that way and decided for this way, because this felt better then having your bullets change course a lot. Try moving your camera closer to the player with the cam_ cvars

**Comment by 0tt** [comment]
I understand the mechanics behind it. It works great for windows and other
transparent brushes where damage location is irrelevant, and 90% of the
time, you're aiming through the object at something else.

Nobody aims through players though. The number one objective of the game is
to aim at players. It's well known that first person is more accurate than
this person and that first person headshots are consistent. I'd say the
number two objective is to kill your opponent as fast as possible. Hence
the importance of headshots.

The primary crosshair is what you aim with. It stays in the center of the
screen, no matter what. If your player (not your camera) doesn't have a
direct line of sight, the secondary crosshair comes in. Nobody aims with
the secondary crosshair. They note its existence, think "I need better
positioning", and aim at something else. The secondary crosshair is an
error. It's a fallback to let somebody know why they're not hitting
something. It can be anywhere from the middle of the screen to the bottom
left corner of the screen. It's not consistent.

When you aim at a player, the game says "Oh! You can't hit this wall 20
feet behind your mortal enemy! Hold on, here's a geometry-dependent
projected location on that gun-touting lunatic so you at least know why
your bullets aren't hitting this wall." Does this sound like good game
design to you? Moving the crosshair required to kill people to completely
lose all sense of precision in where your shots land? Imagine that the
player has a high-powered flashlight at their eyepos. When they look at a
player, a shadow is cast on the scenery behind them. To hit them
accurately, you have to aim at the head *of the shadow* that could be
literally any size behind them. If you want headshots (and by that I mean
if you want to win), you have to be aiming *at least* a few feet above
other players, and each situation requires a recalibration of the mess that
is the fact that the primary crosshair ignores players.

**Comment by BSVino** [comment]
I don't disagree with any particular thing. Björn?

**Comment by TomyLobo** [comment]
I think the actual problem is not having the secondary crosshair on people your line of sight doesn't currently hit.

I don't know if that'd work, though, especially in many-player situations.
It could also be very confusing.

**Comment by BSVino** [comment]
What I mean is: The other way of doing it is that whatever your cursor is on, the character turns to aim at that thing. If there's something near the camera than the character will turn a lot and bullets could go to wildly different locations. You could add support for that and retain support for the current camera system, if you wanted.

**Comment by TomyLobo** [comment]
I too think it would be wildly confusing.
I've played games where it's like that and it takes away from your feeling of agency

**Comment by 0tt** [comment]
Can you define a feeling of agency? Agency as opposed to what? Lethargy?

**Comment by BSVino** [comment]
In the current system the character always shoots forward. In the proposed system the character may shoot to the side if there is a wall adjacent to the character, even if the character could otherwise see and shoot around the wall. I dunno if agency is the right word for it but it does actually limit what you can shoot at a bit, since you can't shoot through things with the proposed system.

**Comment by 0tt** [comment]
What are you on about? All I'm proposing is to change the trace mask in such a way that it hits players as well as the world.

>the character may shoot to the side if there is a wall adjacent

This already happens.

![](http://i.imgur.com/GyoaZmS.png)

**Comment by BSVino** [comment]
Well then what the fuck am I talking about.

Then I'm still not sure what you mean by trace mask. You already have the crosshair hitting the player, that's why it shows the white plus thing.

**Comment by 0tt** [comment]
The primary crosshair is what you aim with. It stays in the center of the
screen, no matter what. If your player (not your camera) doesn't have a
direct line of sight, the secondary crosshair comes in. Nobody aims with
the secondary crosshair. They note its existence, think "I need better
positioning", and aim at something else. The secondary crosshair is an
error. It's a fallback to let somebody know why they're not hitting
something. It can be anywhere from the middle of the screen to the bottom
left corner of the screen. It's not consistent.

When you aim at a player, the game says "Oh! You can't hit this wall 20
feet behind your mortal enemy! Hold on, here's a geometry-dependent
projected location on that gun-touting lunatic so you at least know why
your bullets aren't hitting this wall." Does this sound like good game
design to you? Moving the crosshair required to kill people to completely
lose all sense of precision in where your shots land? Imagine that the
player has a high-powered flashlight at their eyepos. When they look at a
player, a shadow is cast on the scenery behind them. To hit them
accurately, you have to aim at the head *of the shadow* that could be
literally any size behind them. If you want headshots (and by that I mean
if you want to win), you have to be aiming *at least* a few feet above
other players, and each situation requires a recalibration of the mess that
is the fact that the primary crosshair ignores players.

**Comment by TomyLobo** [comment]
I can't really reproduce what you show on your screenshot. can you post the uncropped version?

**Comment by 0tt** [comment]
I had the camera maxed out behind me and to the right. It takes some
fiddling to get the camera to stay behind the wall.

**Comment by TomyLobo** [comment]
Nope, still can't reproduce it. Please post an uncropped version to ctrlv.in or something

**Comment by BSVino** [comment]
OK I was confused before but let's all get on the same page here.

![apunte sin nombre - jul 16 2016 10 04 am - pagina 4](https://cloud.githubusercontent.com/assets/815310/16896049/b9528194-4b3c-11e6-84ca-56c327890ec5.png)

#1 is what happens if you aim at a wall behind an obstruction. The obstruction is between the player character and the point where the camera is aiming, so while the crosshair goes on the wall, the obstruction gets a cross mark on it. The obstruction could be another player or a wall, it doesn't matter, it's handled the same.

#2 is what happens if you aim exactly at the obstruction. The crosshair goes on the obstruction and both the camera and the player character are looking at the same thing. There is no cross mark.

The problem is that if you move even a little bit to the side then you miss the obstruction completely and, and #3 happens. The player character looks much farther to the side, but the crosshair hasn't moved on the player's screen.

So there are actually two ways of aiming at the obstruction, one causes your bullets to go to wildly different locations for slight changes in mouse movement (#2/#3 case) and the other is hard to aim with (#1 case).

The other way of doing a camera system would be to fix the character's view angles to the camera's view angles and move the reticle around the screen depending on what the character is pointing at. That's what I decided against. I like this solution better but obviously it has flaws.

You can't get around the fact that the player character and the player have different views of the world. I'm open to suggestions.

**Comment by 0tt** [comment]
Actually, this is what happens.

![](http://i.imgur.com/iqu8QWn.jpg)

It straight up.ignores that fact that you're trying to hit the player with any sort of precision. It should behave like this:

![](http://i.imgur.com/G0sjSKU.jpg)

**Comment by BSVino** [comment]
Oh OK I see, that's the screenshot you posted in your first post. I think Tomy is on board with it too and I'm playing catchup. Should be something he can fix if he can repro it.

**Comment by 0tt** [comment]
You can't get around wildly changing bullet directions. they weren't going to hit the target anyways, why bother? Directions wildly change when people walk through doorways all the time. It doesn't happen when your camera is centered, but what does matter is that the elevation of your secondary crosshair when aiming at an enemy is much lower than your aiming crosshair, and you have to compensate if you want headshots. Which sucks.

**Comment by TomyLobo** [comment]
Some people actually use full-auto weapons and it's a good strategy there to aim with the tracers. If the tracer direction isn't linear to your mouse movement, how are you going to aim?

**Comment by BSVino** [comment]
Then you may want to make moving-crosshair mode anyway. But I think the fix Ott is requesting is just to make it so that the crosshair trace respects players.

**Comment by TomyLobo** [comment]
I thought you said it does, let me test...

**Comment by TomyLobo** [comment]
The white crosshair is on players, so i guess the crosshair trace does hit players.
It's hitbox-accurate and I think that's what matters.

**Comment by BSVino** [comment]
So you're saying what's happening is that the primary crosshair goes through the player bounding box but the secondary reticle hits it?

**Comment by TomyLobo** [comment]
If the white one is the secondary reticle, yes.

Hmm I see, and that's what distinguishes it from walls and such...

**Comment by TomyLobo** [comment]
The primary reticle being stuck to the middle of the screen is odd anyway... would explain why 1st person cam is off for players who use 3rd person mode.

**Comment by 0tt** [comment]
Why the fuck _wouldn't_ your crosshair be in the middle of the screen? Only Halo does that and that's to make people look up more.

**Comment by TomyLobo** [comment]
because perspective

**Comment by 0tt** [comment]
The primary crosshair always stays in the middle of the screen. It's what you aim with. The secondary crosshair tells you why you won't hit where you're aiming. It moves, and as such is unpredictable. You can't aim with it.

**Comment by 0tt** [comment]
Didn't we come to an understanding six "_but why_"s ago?

**Comment by TomyLobo** [comment]
There's no understanding, we're all confused

**Comment by BSVino** [comment]
Ott, Tomy and I talked about it online and I think we're on the same page about what you're trying to get fixed and it's on his list to fix now. Sorry about the confusion.

**Comment by BSVino** [comment]
We realized that we can't ship this with the next bugfix update because it requires changes that will make the server and client incompatible. But we'll slate it for the next major version which I think is 1.3.

**Comment by ottworks** [comment]
Yay!
Wow I got salty about this issue. My future self apologizes to your past self.

**Comment by TomyLobo** [comment]
Hey, no problem :)

Btw, I'm still not sure whether I should increment the internal version number due to this or not.
What this would do is prevent you from connecting (or even seeing) servers that didn't update yet.

A build containing the fix is up on the "develop" beta branch.
It would be cool if you could test that build on any current server, that'd mirror exactly the situation we'd have post-patch if I don't increment the version.

I'm curious about whether this causes any issues.
I myself usually play 1st person, so I probably couldn't tell the difference.
What we're looking for is any instance of people not hitting where they should.
